---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://10.0.1.1.nip.io/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    enablePasswordDB: true
    oauth2:
      skipApprovalScreen: false
    alwaysShowLoginScreen: true
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 3b6a17515f1970d7cb50
          clientSecret: b1528d5f11f4891ac3e91e69d2f4da9cc3281014
          redirectURI: http://10.0.1.1.nip.io/dex/callback
          useLoginAsID: false
      - type: google
        id: google
        name: Google
        config:
          clientID: 98134702542-k8n7mdo7fgdhfeeemp0nftj94qdjvlfq.apps.googleusercontent.com
          clientSecret: M3f02o0q9ERS64kQqzJw-mTZ
          redirectURI: http://10.0.1.1.nip.io/dex/callback
    staticPasswords:
    - email: tidu@aol.com
      hash: $2a$10$Q8U8ygJQGQNgkfi.H1BBDuVHENV5YMgGyj144T3ygUyoOAO/bXT7W
      username: tidu
    staticClients:
    - id: kubeflow-oidc-authservice
      redirectURIs: ["/login/oidc"]
      name: 'Dex Login Application'
      secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok

