apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
- virtual-service.yaml
- ../../base

patchesStrategicMerge:
- config-map.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml

images:
- name: quay.io/dexidp/dex
  newName: ghcr.io/dexidp/dex
  newTag: v2.30.0